keen/dashboard-creator

- public/locales/en/translation.json
- src/components/Editor/Editor.tsx
- src/components/EditorNavigation/EditorNavigation.tsx
- src/components/ManagementNavigation/ManagementNavigation.tsx
- src/components/QueryPickerModal/QueryPickerModal.tsx
- src/components/Widget/Widget.tsx
https://metakeen.atlassian.net/browse/FEE-245
> chore: 🤖 add missing translations

- src/components/ChartWidget/ChartWidget.tsx
- src/modules/dashboards/saga.ts
- src/modules/theme/index.ts
- src/modules/theme/selectors.ts
https://metakeen.atlassian.net/browse/FEE-261
> refactor: 💡 get active dashboard theme

- src/components/DashboardTile/components/Header/Header.styles.ts
https://metakeen.atlassian.net/browse/FEE-368
> fix: 🐛 height alignment for ff

- src/components/Grid/Grid.tsx
https://metakeen.atlassian.net/browse/FEE-387
> fix: 🐛 set grid compact type

- src/components/DashboardShare/components/EmbedCode/EmbedCode.tsx
- src/components/DashboardShare/components/EmbedCode/constants.ts
- src/components/DashboardShare/components/InputGroup/InputGroup.styles.tsx
- src/components/DashboardShare/components/InputGroup/InputGroup.tsx
- src/components/DashboardShare/constants.ts
- src/components/Grid/Grid.tsx
- src/modules/dashboards/saga.test.ts
- src/modules/dashboards/saga.ts
- src/modules/dashboards/utils/createCodeSnippet.test.ts
- src/modules/dashboards/utils/createCodeSnippet.ts
* revert <Grid> compact mode to default
* update code snippets
* add `Copied to clipboard` tooltip to <InputGroup> component
> refactor: 💡 grid compact mode and copy to clipboard tooltip

- src/components/ImagePicker/ImagePicker.test.tsx
- src/components/ImagePicker/ImagePicker.tsx
- src/modules/queries/actions.ts
- src/modules/queries/constants.ts
- src/modules/queries/index.ts
- src/modules/queries/reducer.test.ts
- src/modules/queries/reducer.ts
- src/modules/queries/types.ts
- src/modules/widgets/actions.ts
- src/modules/widgets/constants.ts
- src/modules/widgets/index.ts
- src/modules/widgets/saga.test.ts
- src/modules/widgets/saga.ts
- src/rootReducer.ts
added reducer for interim queries + missing unit tests for image picker
> chore: 🤖 interim queries reducer

- src/modules/dashboards/saga.test.ts
- src/modules/dashboards/saga.ts
https://metakeen.atlassian.net/browse/FEE-388
> feat: 🎸 queries count

- public/locales/en/translation.json
- src/components/DashboardTile/DashboardTile.test.tsx
- src/components/DashboardTile/DashboardTile.tsx
https://metakeen.atlassian.net/browse/FEE-388
> chore: 🤖 update labels for queries count

- src/components/RelativeTimeLabel/RelativeTimeLabel.styles.ts
- src/components/RelativeTimeLabel/RelativeTimeLabel.test.tsx
- src/components/RelativeTimeLabel/RelativeTimeLabel.tsx
- src/components/TimeframeLabel/TimeframeLabel.tsx
> fix: 🐛 add icon to <RelativeTimeLabel>

- src/components/DatePickerWidget/DatePickerWidget.styles.ts
- src/components/DatePickerWidget/DatePickerWidget.tsx
https://projects.invisionapp.com/d/main#/console/21040432/444820082/preview
> style: 💄 update <DatePickerWidget> spacing

- src/components/Grid/constants.ts
- src/components/Toolbar/utils/calculateGhostSize.test.ts
https://metakeen.atlassian.net/browse/FEE-236
> fix: 🐛 update grid row height

- src/components/DatePickerManagement/DatePickerManagement.styles.ts
- src/components/DatePickerManagement/DatePickerManagement.tsx
https://metakeen.atlassian.net/browse/FEE-236
> fix: 🐛 DatePickerManagement width

- src/components/Widget/Widget.styles.ts
- src/components/Widget/Widget.tsx
- src/components/Widget/components/WidgetCover/WidgetCover.styles.tsx
https://metakeen.atlassian.net/browse/FEE-236
> fix: 🐛 add border radius for highlighted widget

- src/components/DatePickerWidget/DatePickerWidget.styles.ts
- src/components/DatePickerWidget/DatePickerWidget.tsx
https://metakeen.atlassian.net/browse/FEE-236
> style: 💄 add active state for <DatePickerWidget>

- src/components/Editor/Editor.tsx
- yarn.lock
https://metakeen.atlassian.net/browse/FEE-380
> fix: 🐛 remove Infinity from widget position

- src/components/ChartWidgetFilter/ChartWidgetFilter.tsx
- src/modules/widgets/saga/chartWidget.ts
> fix: 🐛 split of undefined resolved

- src/modules/dashboards/saga.test.ts
- src/modules/dashboards/saga.ts
https://metakeen.atlassian.net/browse/FEE-439
> fix: 🐛 handle api errors when creating an access key

- src/components/DashboardShare/components/InputGroup/InputGroup.tsx
- src/components/DashboardShare/components/PublicLink/PublicLink.tsx
https://metakeen.atlassian.net/browse/FEE-440
> fix: 🐛 disable copy to clipboard for null public key

- src/modules/dashboards/reducer.ts
https://metakeen.atlassian.net/browse/FEE-438
> fix: 🐛 change position of newly added widget

- src/components/Editor/Editor.tsx
- src/components/Grid/Grid.styles.ts
- src/components/Grid/Grid.tsx
- src/constants.ts
- src/modules/dashboards/actions.ts
- src/modules/dashboards/constants.ts
- src/modules/dashboards/saga.test.ts
- src/modules/dashboards/saga.ts
- src/modules/dashboards/utils/findBiggestYPositionOfWidgets.test.ts
- src/modules/dashboards/utils/findBiggestYPositionOfWidgets.ts
- src/modules/widgets/__snapshots__/reducer.test.ts.snap
- src/modules/widgets/reducer.ts
- src/modules/widgets/saga.test.ts
- src/modules/widgets/saga.ts
Z-index on widget management hover fixed, Setting position of cloned and
new widgets at the end of the dashboard, tests added
[FEE-448](https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-448)
[FEE-438](https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-438)
> chore: 🤖 React responsive grid - layouts handling change

- src/components/TextManagement/TextManagement.styles.ts
- src/components/TextManagement/TextManagement.tsx
https://metakeen.atlassian.net/browse/FEE-425
> style: 💄 update styles for <TextWidgetManagement>

- src/components/Grid/Grid.tsx
- src/components/Grid/constants.ts
- src/components/Toolbar/types.ts
- src/components/Toolbar/utils/calculateGhostSize.ts
Closes: [FEE-490](https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-490)
> fix: 🐛 Dashboard grid columns number in edit mode set to 12

- public/locales/en/translation.json
- src/components/DatePickerWidget/DatePickerWidget.styles.ts
- src/components/DatePickerWidget/DatePickerWidget.tsx
- yarn.lock
https://metakeen.atlassian.net/browse/FEE-485
> feat: 🎸 add notification about presentation timezone

- src/components/DashboardTile/components/Header/Header.styles.ts
- src/components/DashboardTile/components/Header/Header.tsx
https://metakeen.atlassian.net/browse/FEE-496
> fix: 🐛 unify tags presentation

- .circleci/config.yml
- README.md
- jest.config.js
- package.json
- yarn.lock
Closes: [FEE-478](https://metakeen.atlassian.net/browse/FEE-478)
> chore: 🤖 Codecov added to the project

- .gitignore
https://metakeen.atlassian.net/browse/FEE-523
> refactor: 💡 update gitignore

- src/components/TextWidget/TextWidget.styles.ts
https://metakeen.atlassian.net/browse/FEE-532
> fix: 🐛 nonbreaking text in TextWidget

- public/locales/en/translation.json
- src/components/ChartWidgetEditor/components/ChartEditor/ChartEditor.test.tsx
- src/components/ChartWidgetEditor/components/ChartEditor/ChartEditor.tsx
- src/modules/chartEditor/actions.ts
- src/modules/chartEditor/reducer.test.ts
- src/modules/chartEditor/reducer.ts
- src/modules/chartEditor/saga.test.ts
- src/modules/chartEditor/saga.ts
- src/modules/chartEditor/types.ts
Closes: [FEE-547](https://metakeen.atlassian.net/browse/FEE-547)
> fix: 🐛 Disabled ability to save dirty query

- src/components/DashboardListOrder/DashboardListOrder.styles.ts
- src/components/DashboardListOrder/DashboardListOrder.tsx
- src/components/FilterDashboards/FilterDashboards.styles.ts
- src/components/FilterDashboards/FilterDashboards.tsx
- src/components/FilterDashboards/components/FilterItem/FilterItem.styles.ts
- src/components/FilterDashboards/components/FilterItem/FilterItem.tsx
https://metakeen.atlassian.net/browse/FEE-519
> style: 💄 dashboard management

- src/components/ChartWidgetEditor/components/ChartEditor/ChartEditor.test.tsx
- src/components/ChartWidgetEditor/components/ChartEditor/ChartEditor.tsx
- src/components/ChartWidgetEditor/components/ChartEditor/constants.ts
- src/components/ChartWidgetEditor/components/ChartEditor/types.ts
[https://metakeen.atlassian.net/browse/FEE-552](https://metakeen.atlassian.net/browse/FEE-552)
> fix: 🐛 Disabling "add to dashboard" button when analysisResult is empty

- src/components/TextManagement/TextManagement.styles.ts
- src/components/TextManagement/TextManagement.tsx
https://metakeen.atlassian.net/browse/FEE-534
> fix: 🐛 text widget position

- src/App.styles.ts
- src/components/DashboardTile/components/Placeholder/Placeholder.tsx
- src/components/DashboardTile/components/Placeholder/__snapshots__/Placeholder.test.tsx.snap
- src/components/DashboardsList/DashboardsList.styles.ts
- src/components/Editor/Editor.styles.ts
- src/components/Management/Management.styles.ts
- src/components/Management/Management.tsx
- src/components/ManagementNavigation/ManagementNavigation.styles.ts
- src/components/PublicDashboardViewer/PublicDashboardViewer.styles.ts
- src/components/Viewer/Viewer.styles.ts
https://metakeen.atlassian.net/browse/FEE-568
> fix: 🐛 update dashboards management grid

- src/components/ChartWidgetEditor/components/WidgetVisualization/WidgetVisualization.styles.ts
- yarn.lock
https://metakeen.atlassian.net/browse/FEE-566
> fix: 🐛 add relative context to WidgetContainer

- src/components/ChartWidgetEditor/components/ChartEditor/ChartEditor.styles.ts
- src/components/ChartWidgetEditor/components/ChartEditor/ChartEditor.tsx
- yarn.lock
https://metakeen.atlassian.net/browse/FEE-582
> style: 💄 bump libs and unify containers

- src/components/WidgetConnections/WidgetConnections.styles.ts
- src/components/WidgetConnections/WidgetConnections.tsx
- yarn.lock
* resolves https://metakeen.atlassian.net/browse/FEE-586
* need to bump keen.io/ui-core from https://github.com/keen/keen/pull/917
> fix: 🐛 WidgetConnections alignment

- src/components/ChartWidgetEditor/components/WidgetVisualization/WidgetVisualization.styles.ts
- yarn.lock
https://metakeen.atlassian.net/browse/FEE-566
> fix: 🐛 bump keen dependencies and revert css changes

- yarn.lock
https://metakeen.atlassian.net/browse/FEE-594
> chore: 🤖 bump keen dependencies

- src/api/BlobAPI.test.ts
- src/api/BlobAPI.ts
- src/modules/dashboards/saga.test.ts
- src/modules/dashboards/saga.ts
https://metakeen.atlassian.net/browse/FEE-591
> refactor: 💡 getDashboardMetaDataById method

- yarn.lock
bump keen dependencies for https://metakeen.atlassian.net/browse/FEE-500
> feat: 🎸 table descriptive columns

- public/locales/en/translation.json
- src/components/DashboardListOrder/DashboardListOrder.test.tsx
- src/components/DashboardListOrder/DashboardListOrder.tsx
- src/components/Management/Management.test.tsx
- src/components/Management/Management.tsx
- src/modules/dashboards/constants.ts
https://metakeen.atlassian.net/browse/FEE-520
> fix: 🐛 dashboards empty state

- src/components/TextManagement/TextManagement.styles.ts
- src/components/TextManagement/TextManagement.tsx
- src/components/TextManagement/constants.ts
https://metakeen.atlassian.net/browse/FEE-623
> feat: 🎸 improve ux for TextWidget delete

- src/components/FilterManagement/FilterManagement.styles.ts
- src/components/FilterManagement/FilterManagement.tsx
- src/components/FilterManagement/constants.ts
- src/components/RemoveWidget/RemoveWidget.styles.ts
https://metakeen.atlassian.net/browse/FEE-637
> fix: 🐛 remove widget positioning

- src/components/ChartWidgetFilter/components/WidgetFilter/WidgetFilter.tsx
- src/components/DatePickerWidget/DatePickerWidget.tsx
- src/components/FilterWidget/FilterWidget.tsx
https://metakeen.atlassian.net/browse/FEE-661
> style: 💄 widget filter icons

- src/components/TextManagement/TextManagement.styles.ts
- src/components/TextWidget/TextWidget.styles.ts
- src/components/TextWidget/index.ts
- src/components/Widget/Widget.styles.ts
https://metakeen.atlassian.net/browse/FEE-652
> style: 💄 update styles for TextWidget

- src/components/FilterManagement/FilterManagement.styles.ts
- src/components/RemoveWidget/RemoveWidget.styles.ts
- src/components/TextManagement/TextManagement.styles.ts
- src/components/TextManagement/constants.ts
https://metakeen.atlassian.net/browse/FEE-623
> fix: 🐛 unify deleting widgets

- src/components/RelativeTimeLabel/RelativeTimeLabel.tsx
- src/components/TimeframeLabel/TimeframeLabel.tsx
https://metakeen.atlassian.net/browse/FEE-661
> style: 💄 fixing styles for applied timeframe icons

- src/components/ChartWidget/ChartWidget.test.tsx
- src/components/ChartWidget/ChartWidget.tsx
- src/components/ChartWidget/utils/createDataviz.ts
- src/components/Widget/Widget.styles.ts
- src/components/Widget/Widget.tsx
- src/modules/theme/utils/getColorSuggestions.test.ts
- src/modules/theme/utils/getColorSuggestions.ts
Default background color added to color suggestions
> fix: 🐛 Table chart fixes

- src/App.styles.ts
- src/components/Grid/constants.ts
- src/components/PublicDashboardViewer/PublicDashboardViewer.styles.ts
https://metakeen.atlassian.net/browse/FEE-589
> fix: 🐛 set grid layout breakpoints

- src/components/Editor/Editor.styles.ts
https://metakeen.atlassian.net/browse/FEE-701
> fix: 🐛 update EditorBar margin

- src/modules/widgets/saga/filterWidget.test.ts
- src/modules/widgets/saga/filterWidget.ts
https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-682
> feat: 🎸 Filter list items sorted alphabetically

- src/components/EditorNavigation/EditorNavigation.styles.ts
- src/components/Viewer/Viewer.styles.ts
https://metakeen.atlassian.net/browse/FEE-716
> style: 💄 reset navigation padding

- src/components/DashboardViewSwitch/DashboardViewSwitch.styles.ts
- src/components/DashboardViewSwitch/DashboardViewSwitch.tsx
https://metakeen.atlassian.net/browse/FEE-714
> style: 💄 fix footer layout

- src/components/Editor/customHooks/useMarkerRef.ts
- src/components/EditorBar/EditorBar.styles.ts
https://metakeen.atlassian.net/browse/FEE-708
> fix: 🐛 add animation for sticky bar shadow

- public/locales/en/translation.json
- src/components/ChartWidget/ChartWidget.tsx
- src/components/Viewer/Viewer.tsx
- src/components/ViewerNavigation/ViewerNavigation.styles.ts
- src/components/ViewerNavigation/ViewerNavigation.test.tsx
- src/components/ViewerNavigation/ViewerNavigation.tsx
- src/components/ViewerNavigation/components/index.ts
- src/modules/dashboards/actions.ts
- src/modules/dashboards/constants.ts
- src/modules/dashboards/dashboardsSaga.test.ts
- src/modules/dashboards/dashboardsSaga.ts
- src/modules/dashboards/index.ts
- src/modules/dashboards/saga/index.ts
- src/modules/dashboards/saga/resetDashboardFilters.test.ts
- src/modules/dashboards/saga/resetDashboardFilters.ts
- src/modules/queries/index.ts
- src/modules/queries/selectors.ts
https://metakeen.atlassian.net/browse/FEE-495
> feat: 🎸 clear active filters

- src/modules/dashboards/dashboardsSaga.test.ts
- src/modules/dashboards/dashboardsSaga.ts
- src/modules/dashboards/saga/deleteAccessKey.ts
- src/modules/dashboards/saga/deleteDashboard.test.ts
- src/modules/dashboards/saga/deleteDashboard.ts
- src/modules/dashboards/saga/index.ts
- src/modules/dashboards/selectors.ts
- src/modules/widgets/saga/datePickerWidget.ts
- src/modules/widgets/saga/filterWidget.ts
get rid of runtime error after dashboard is removed
> fix: 🐛 dashboard remove

- src/components/DashboardDetails/DashboardDetails.styles.ts
- src/components/DashboardDetails/DashboardDetails.tsx
- src/components/PublicDashboardViewer/PublicDashboardViewer.styles.ts
- src/components/PublicDashboardViewer/PublicDashboardViewer.test.tsx
- src/components/PublicDashboardViewer/PublicDashboardViewer.tsx
https://metakeen.atlassian.net/browse/FEE-495
> feat: 🎸 add clear filters to public dashboard

- src/components/DashboardTile/DashboardTile.styles.ts
- src/components/DashboardTile/motions.ts
https://metakeen.atlassian.net/browse/FEE-736
> fix: 🐛 dashboard tile animation

- src/components/Editor/Editor.styles.ts
- src/components/Editor/Editor.tsx
https://metakeen.atlassian.net/browse/FEE-733
> fix: 🐛 sticky bar overflow

- src/DashboardCreator.tsx
- src/components/EditorBar/EditorBar.test.tsx
- src/components/EditorBar/EditorBar.tsx
- src/components/PermissionGate/utils/hasPermission.ts
- src/modules/app/types.ts
https://metakeen.atlassian.net/browse/FEE-745
> feat: 🎸 edit theme feature flag

- package.json
- public/locales/en/translation.json
- src/components/ThemeEditor/components/ChartSettings/components/Axis/Axis.test.tsx
- src/components/ThemeEditor/components/ChartSettings/components/Axis/Axis.tsx
- src/components/ThemeEditor/components/ChartSettings/components/Axis/constants.ts
- yarn.lock
support for providing axis title from user interface
> feat: 🎸 axis titles

- src/components/ChartWidget/ChartWidget.styles.ts
https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-726
> fix: 🐛 Choropleth interactions fix

- src/components/ChartWidgetEditor/components/ChartEditor/ChartEditor.styles.ts
- src/components/ChartWidgetEditor/components/ChartEditor/ChartEditor.test.tsx
- src/components/ChartWidgetEditor/components/ChartEditor/ChartEditor.tsx
- src/components/TextWidgetEditor/components/Editor/Editor.styles.ts
- src/components/TextWidgetEditor/components/Editor/Editor.tsx
https://metakeen.atlassian.net/browse/FEE-737
> fix: 🐛 close indicators added to text/chart modals

- public/locales/en/translation.json
https://metakeen.atlassian.net/browse/FEE-587
> fix: 🐛 add missing translation

- src/components/Widget/Widget.tsx
- src/components/Widget/types.ts
https://metakeen.atlassian.net/browse/FEE-751
> fix: 🐛 edit widget when initialized

- yarn.lock
https://metakeen.atlassian.net/browse/FEE-734
> chore: 🤖 bump ui-core to fix accordion animation glitch

- src/components/ThemeEditor/components/ChartSettings/ChartSettings.tsx
- src/components/ThemeEditor/components/ChartSettings/components/Axis/Axis.tsx
- src/components/ThemeEditor/components/ChartSettings/components/Legend/Legend.tsx
- src/components/ThemeEditor/components/ChartSettings/components/Titles/Titles.tsx
- src/components/ThemeEditor/components/Visualizations/Visualizations.tsx
- yarn.lock
https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-779
> Fix - missing color suggestions, copy/paste

- src/components/Editor/Editor.tsx
- src/modules/dashboards/actions.ts
- src/modules/dashboards/constants.ts
- src/modules/dashboards/dashboardsSaga.ts
- src/modules/dashboards/saga/finishDashboardEdition.test.ts
- src/modules/dashboards/saga/finishDashboardEdition.ts
- src/modules/dashboards/saga/index.ts
https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-780
> feat: 🎸 Trigger Dashboard Settings on "Finish Edition" click

- src/components/Grid/Grid.tsx
- src/components/RelativeTimeLabel/RelativeTimeLabel.styles.ts
- src/components/RelativeTimeLabel/RelativeTimeLabel.tsx
- src/components/TimeframeLabel/TimeframeLabel.styles.tsx
- src/components/TimeframeLabel/TimeframeLabel.tsx
- src/utils/getDroppingItemSize.ts
* https://metakeen.atlassian.net/browse/FEE-776
* https://staging-static.keen.io/build/style/FEE-776-date-picker/index.html
> style: 💄 responsive Date Picker

- src/components/DashboardTile/components/Header/Header.styles.ts
- src/components/DashboardTile/components/Header/Header.tsx
https://metakeen.atlassian.net/browse/FEE-790
> style: 💄 update dashboard tags

- public/dashboard-creator.html
- public/locales/en/translation.json
- src/DashboardCreator.tsx
- src/components/ConfirmQueryChange/ConfirmQueryChange.test.tsx
- src/components/ConfirmQueryChange/ConfirmQueryChange.tsx
- src/components/Editor/Editor.tsx
- src/constants.ts
- src/contexts/AppContext.ts
- src/createSagaMiddleware.ts
- src/modules/widgets/saga/chartWidget.test.ts
- src/modules/widgets/saga/chartWidget.ts
- src/types.ts
* https://metakeen.atlassian.net/browse/FEE-796
* https://staging-static.keen.io/build/feat/FEE-796-feature-flag/index.html
> feat: 🎸 feature flag

- src/modules/dashboards/saga/saveDashboard.test.ts
- src/modules/dashboards/utils/computeDashboardMetadata.test.ts
- src/modules/dashboards/utils/computeDashboardMetadata.ts
https://metakeen.atlassian.net/browse/FEE-583
> fix: 🐛 queries counter

- public/locales/en/translation.json
https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-789
> fix: 🐛 Order by - result of analysis label fixed

- src/components/ChartWidgetEditor/components/ChartEditor/ChartEditor.tsx
https://metakeen.atlassian.net/browse/FEE-838
> fix: 🐛 table chart edit mode

- package.json
- yarn.lock
https://metakeen.atlassian.net/browse/FEE-839
> chore: 🤖 bump widget customization

- src/components/ThemeEditor/components/ChartSettings/ChartSettings.tsx
- src/components/ThemeEditor/components/ColorManager/ColorManager.test.tsx
- src/components/ThemeEditor/components/ColorManager/ColorManager.tsx
- src/components/ThemeEditor/components/DashboardPage/DashboardPage.tsx
- src/components/ThemeEditor/components/MainSettings/MainSettings.tsx
- src/components/ThemeEditor/components/Visualizations/Visualizations.tsx
- src/components/ThemeEditor/components/WidgetTiles/WidgetTiles.tsx
- src/modules/theme/constants.ts
- src/modules/theme/utils/getColorSuggestions.ts
https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10/backlog?selectedIssue=FEE-829
> fix: 🐛 Color suggestions fix in theming

- public/locales/en/translation.json
- src/components/ViewerNavigation/ViewerNavigation.styles.ts
https://metakeen.atlassian.net/browse/FEE-818
> chore: 🤖 fix clear all filters typography

- public/locales/en/translation.json
- src/components/DatePickerSettings/DatePickerSettings.styles.ts
- src/components/DatePickerSettings/DatePickerSettings.test.tsx
- src/components/DatePickerSettings/DatePickerSettings.tsx
- src/components/FilterSettings/FilterSettings.styles.ts
- src/components/FilterSettings/FilterSettings.test.tsx
- src/components/FilterSettings/FilterSettings.tsx
- src/components/FilterSettings/components/TooltipHint/TooltipHint.styles.ts
https://metakeen.atlassian.net/browse/FEE-820
> chore: 🤖 select/unselect all in filter configuration

- src/components/TextWidgetEditor/TextWidgetEditor.styles.ts
- src/components/TextWidgetEditor/TextWidgetEditor.tsx
https://metakeen.atlassian.net/browse/FEE-510
> style: 💄 add loader to TextWidget

- src/components/Grid/Grid.tsx
- src/modules/dashboards/dashboardsSaga.test.ts
- src/modules/dashboards/dashboardsSaga.ts
- src/modules/widgets/widgetsSaga.test.ts
- src/modules/widgets/widgetsSaga.ts
- src/utils/index.ts
- src/utils/scrollItemIntoView.ts
https://metakeen.atlassian.net/browse/FEE-702
> feat: 🎸 scroll to cloned/added widget

- src/components/DashboardTile/DashboardTile.styles.ts
- src/components/DashboardTile/DashboardTile.tsx
https://staging-static.keen.io/build/fix/cropped-actions-menu/index.html
> fix: 🐛 cropped actions menu

- package.json
- public/locales/en/translation.json
- yarn.lock
https://metakeen.atlassian.net/browse/FEE-600
> fix: 🐛 empty target value for Gauge

- package.json
- yarn.lock
https://metakeen.atlassian.net/browse/FEE-871
> chore: 🤖 bump widget-customization

- src/components/FilterWidget/FilterWidget.tsx
https://metakeen.atlassian.net/browse/FEE-854
> fix: 🐛 filter property list

- docs/dashboard.md
- jest.config.js
- public/locales/en/translation.json
- src/components/EditorBar/EditorBar.test.tsx
- src/components/EditorBar/EditorBar.tsx
- src/modules/dashboards/dashboardsSaga.test.ts
- src/modules/dashboards/dashboardsSaga.ts
- src/modules/dashboards/types.ts
- src/modules/dashboards/utils/createDashboardMeta.ts
https://metakeen.atlassian.net/browse/FEE-728
> chore: 🤖 update Dashboard auto-save

- src/components/DashboardDetails/DashboardDetails.styles.ts
- src/components/DashboardDetails/DashboardDetails.tsx
- src/components/DashboardViewSwitch/DashboardViewSwitch.styles.ts
- src/components/DashboardViewSwitch/DashboardViewSwitch.tsx
https://metakeen.atlassian.net/browse/FEE-104
> style: 💄 handle long labels

- package.json
- yarn.lock
https://metakeen.atlassian.net/browse/FEE-908
> chore: 🤖 bump widget picker
